user              nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log error;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;
    use                epoll;
    multi_accept       on;
}

http {
    include       /etc/nginx/mime.types;
    types {
       application/javascript mjs;
    }
    default_type  application/octet-stream;

    client_max_body_size 50M;

    # prevents 502 Bad Gateway error
    large_client_header_buffers 8 32k;

    # Map to fix CloudFront-Viewer-Address header format, remove brackets and add port
    map $http_cloudFront_viewer_address $fixed_cloudfront_viewer_address {
        default $http_cloudfront_viewer_address;
        "~^([0-9.]+):([0-9]+)$" "$1";
    }

    # Map to check if CloudFront-Viewer-Address header is present and set real ip header value
    map $http_cloudFront_viewer_address $real_ip_header_value {
        default $http_x_forwarded_for;
        "~.+$" $fixed_cloudfront_viewer_address;
    }


    # Map to check if CloudFront-Viewer-Address header is present and set remote addr value
    map $http_cloudFront_viewer_address $remote_addr_value {
        default $remote_addr;
        "~.+$" $fixed_cloudfront_viewer_address;
    }


    # Set real ip if request forwarded from VPC (vpc-dc2d9fb9) CIDR
    set_real_ip_from 10.16.0.0/16;
    real_ip_header $real_ip_header_value;
    real_ip_recursive on;

    # Log in JSON Format and exclude Health Checks
    log_format json_main escape=json
    '{'
        '"timestamp": "$time_iso8601",'
        '"time_local":"$time_local",'
        '"network":{"client":{"ip":"$real_ip_header_value"}},'
        '"remote_addr": "$real_ip_header_value",'
        '"remote_user": "$real_ip_header_value",'
        '"body_bytes_sent": $body_bytes_sent,'
        '"request_time": $request_time,'
        '"status": $status,'
        '"request": "$request",'
        '"request_method": "$request_method",'
        '"host": "$host",'
        '"http_x_forwarded_for": "$http_x_forwarded_for",'
        '"http_referrer": "$http_referer",'
        '"http_user_agent": "$http_user_agent",'
        '"http_version": "$server_protocol",'
        '"amzn_trace_id": "$http_x_amzn_trace_id",'
        '"request_time": "$request_time",'
        '"upstream_connect_time": "$upstream_connect_time",'
        '"upstream_header_time": "$upstream_header_time",'
        '"upstream_response_time": "$upstream_response_time"'
        '"cloudFront_viewer_address": "$fixed_cloudfront_viewer_address",'
   '}';

    map $http_user_agent $exclude_healthcheck {
        "ELB-HealthChecker/2.0" 0;
        default 1;
    }

    access_log /var/log/nginx/access.log json_main if=$exclude_healthcheck;

    # Disables emitting nginx version on error pages and in the “Server” response header field.
    server_tokens off;

    # Sendfile copies data between one FD and other from within the kernel.
    # More efficient than read() + write(), since the requires transferring data to and from the user space.
    sendfile on;

    # Tcp_nopush causes nginx to attempt to send its HTTP response head in one packet,
    # instead of using partial frames. This is useful for prepending headers before calling sendfile,
    # or for throughput optimization.
    tcp_nopush on;

    # don't buffer data-sends (disable Nagle algorithm). Good for sending frequent small bursts of data in real time.
    tcp_nodelay on;

    # Timeout for keep-alive connections. Server will close connections after this time.
    keepalive_timeout 30;

    # allow the server to close the connection after a client stops responding. Frees up socket-associated memory.
    reset_timedout_connection on;

    # send the client a "request timed out" if the body is not loaded by this time. Default 60.
    client_body_timeout 30;

    # If the client stops reading data, free up the stale client connection after this much time. Default 60.
    send_timeout 10;

    include /etc/nginx/conf.d/*.conf;
}
