name: Update Plugin
run-name: Update ${{ inputs.prefix }} plugin to ${{ inputs.tag }}
on:
   workflow_dispatch:
      inputs:
         repository:
            type: string
            default: plugin_HRTeams
         tag:
            description: Release Tag
            type: string
            required: true
         filename:
            description: Release .zip file
            type: string
            required: true
         prefix:
            description: file prefix
            type: string
            required: true
jobs:
   update-plugin:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
           with:
              path: web
         - run: rm -f ./assets/tenant/default/${{ inputs.prefix }}*
           working-directory: web
         - name: Generate a token
           id: generate-token
           uses: actions/create-github-app-token@v2
           with:
              app-id: ${{ vars.GS_DEV_APP_ID }}
              private-key: ${{ secrets.GS_DEV_APP_PK }}
              repositories: ${{ inputs.repository }}
         - uses: robinraju/release-downloader@v1
           with:
              repository: ${{ github.repository_owner }}/${{ inputs.repository }}
              tag: ${{ inputs.tag }}
              filename: ${{ inputs.filename }}
              extract: true
              token: ${{ steps.generate-token.outputs.token }}
         - run: ls
         - run: mv build/* web/assets/tenant/default
         - uses: EndBug/add-and-commit@v9
           with:
              cwd: web
              message: Update ${{ inputs.prefix }} to ${{ inputs.tag }}
              new_branch: ${{ inputs.prefix }}/${{ inputs.tag }}
              default_author: github_actions
