name: "Update Webpack Files"
on:
  workflow_call:
    inputs:
      web_ref:
        description: Reference for service web to checkout
        required: true
        type: string
      repository:
        description: Full repo name without organization
        required: true
        type: string
      short_name:
        description: Short name for the repo
        required: true
        type: string
      path:
        description: Checkout path (web will checkout to /web)
        required: true
        type: string
      version:
        type: string
        required: true
      webpack:
        description: 'webpack build command (npm run build:[command])'
        required: true
        type: string
      pre_release:
        type: string
        required: false
      app_id:
        description: GitHub APP ID for Auth (of Client ID)
        type: string
    secrets:
      app_secret:
        description: GitHub APP Client Secret for Auth
        required: true
      SENTRY_AUTH_TOKEN:
        required: false
    outputs:
      branch: 
        value: ${{ jobs.update-files.outputs.branch }}
jobs:
  update-files:
    name: Update Web Files
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.set_branch.outputs.branch }}
    steps:
      - name: Set branch name
        id: set_branch
        env:
          SHORT_NAME: ${{ inputs.short_name }}
          VERSION: ${{ inputs.version }}
          PRE: ${{ inputs.pre_release != '' && '-' || '' }}${{ inputs.pre_release }}
        run: echo "branch=CI/update$PRE/$SHORT_NAME-$VERSION" >> "$GITHUB_OUTPUT"

      - name: Checkout Service Web
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.web_ref }}
          path: web

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ inputs.app_id }}
          private-key: ${{ secrets.app_secret }}
          repositories: ${{ inputs.repository }}
        
      - name: Checkout Webpack Repo
        uses: actions/checkout@v4
        with:
          ref: v${{ inputs.version }}
          token: ${{ steps.generate-token.outputs.token }}
          submodules: recursive
          repository: ${{ github.repository_owner }}/${{ inputs.repository }}
          path: ${{ inputs.path }}

      - run: npm i
        working-directory: ./${{ inputs.path }}

      - run: npm run build:${{ inputs.webpack }}
        working-directory: ./${{ inputs.path }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Commit Change to New Branch
        id: commit_version
        uses: EndBug/add-and-commit@v9
        with:
          cwd: ./web
          message: Update platform_web to ${{ inputs.VERSION }}
          new_branch: ${{ steps.set_branch.outputs.branch }}
          default_author: github_actions
